### ISSUE TITLE
NoClassDefFoundError 

### ISSUE THREAD

**Issue by ranjansudhir1** [SamsungDForum/SmartViewSDKHelloWorld#2]
hi 
 i try with that sample code but every time i am getting "NoClassDefFoundError". I made one sample using "android-msf-api-2.0.16.jar" but here also i get the same issue which is "NoClassDefFoundError"
initialization of  Search class itself i am getting these error.

**Comment by RockingPrafull** [comment]
Hello,
HelloWorld Android code is ported from Eclipse to Android Studio.
Use Android Studio to build this code. I hope it resolves your problem.
Thanks
