### ISSUE TITLE
multiscreen.samsung.com is not responding

### ISSUE THREAD

**Issue by romaroma** [SamsungDForum/SmartViewSDKHelloWorld#3]
The mobile js app is trying to connect the following address:
http://multiscreen.samsung.com/discoveryservice/v2/discover

Which is not responding, connection is timed out.

**Comment by monster-mj** [comment]
Hi, romaroma
Discoverer Server has been stopped temporarily and then server have been recovered.
Please, test again.
Also, you can try to our test server(same js source)

HelloWorld
MOBILE : http://dev-multiscreen-examples.s3-website-us-west-1.amazonaws.com/examples/helloworld/mobile/

**Comment by romaroma** [comment]
Sorry @monster-mj we have the same story:

msf.min.js:1 GET http://multiscreen.samsung.com/discoveryservice/v2/discover net::ERR_CONNECTION_TIMED_OUT

**Comment by azangru** [comment]
+1

I have been checking http://multiscreen.samsung.com/discoveryservice/v2/discover since early this April or perhaps March, and it has never responded. I was wondering if anyone could shed any light on when the Discovery Server is expected to become operational again.

**Comment by monster-mj** [comment]
I'm sorry

**Comment by monster-mj** [comment]
I'm sorry to late response, 
Discover server stopped again, check it please.

**Comment by chrisland** [comment]
+1
is there any solution?

**Comment by monster-mj** [comment]
Hi, Guys
Sorry to late response
JS Library is updated to fix ther discovery issue.
plz, download new version js 2.3.1
https://www.samsungdforum.com/AddLibrary/SmartViewDownload

**Comment by azangru** [comment]
Yay! The discovery server is responding now. That’s great news!
