### ISSUE TITLE
Error: cannot find symbol class HelloWorldWebApplicationHelper

### ISSUE THREAD

**Issue by vitalets** [SamsungDForum/SmartViewSDKHelloWorld#5]
Hi,

I've made all steps by readme, but can't compile project:
```
Error:(17, 13) error: cannot find symbol class HelloWorldWebApplicationHelper
...
```

could you help?

**Comment by monster-mj** [comment]
Sorry, @vitalets 
I updated fixed android version.
plz check it. thanks

**Comment by vitalets** [comment]
@monster-mj thanks a lot! Could you kindly point a commit here for me just know what was missing..

**Comment by monster-mj** [comment]
I closed this issue
