### ISSUE TITLE
Needs to be updated to swift 3.0.2

### ISSUE THREAD

**Issue by ekimia** [SamsungDForum/SmartViewSDKHelloWorld#6]

**Comment by monster-mj** [comment]
Hi, @ekimia 
plz, replace smartview.framework "iOS Package(Mobile) 8.1 & 8.2" in your local project
http://developer.samsung.com/tv/develop/tools/extension-libraries/smartview-sdk-download

also, I'll change latest framework all of sample iOS app in gitHub
